"""Plotting helpers for arrangement demonstrations."""

from __future__ import annotations

from itertools import combinations
from typing import Iterable, Optional, Sequence, Tuple


def segment_from_row(row, xlim: Tuple[float, float], ylim: Tuple[float, float]):
    """Return the visible segment of an affine line row ``a*x + b*y + c = 0``."""
    a, b, c = [float(x) for x in row]
    eps = 1e-9
    points = []

    if abs(a) < eps and abs(b) < eps:
        return None

    for x in xlim:
        if abs(b) >= eps:
            y = (-c - a * x) / b
            if ylim[0] - eps <= y <= ylim[1] + eps:
                points.append((x, y))

    for y in ylim:
        if abs(a) >= eps:
            x = (-c - b * y) / a
            if xlim[0] - eps <= x <= xlim[1] + eps:
                points.append((x, y))

    unique = []
    seen = set()
    for point in points:
        rounded = (round(point[0], 10), round(point[1], 10))
        if rounded not in seen:
            unique.append(point)
            seen.add(rounded)

    if len(unique) < 2:
        return None
    return unique[0], unique[1]


def affine_intersection(row1, row2):
    """Return the intersection of two affine line rows, or ``None`` if parallel."""
    from sage.all import QQ, matrix, vector

    system = matrix(QQ, [[row1[0], row1[1]], [row2[0], row2[1]]])
    if system.det() == 0:
        return None
    rhs = vector(QQ, [-row1[2], -row2[2]])
    sol = system.solve_right(rhs)
    return float(sol[0]), float(sol[1])


def hyperplanes_through_flat(A, indices: Sequence[int]):
    """Return all hyperplane indices of ``A`` containing the flat generated by ``indices``."""
    submat = A.mat[list(indices), :]
    if submat.rank() != A.n - 1:
        return tuple()
    row_space = submat.row_space()
    return tuple(i for i, row in enumerate(A.mat.rows()) if row in row_space)


def constructive_points(A, subset_indices: Iterable[int]):
    """Return visible constructive-closure points for a rank-3 affine chart demo."""
    points = []
    seen = set()
    for flat in combinations(sorted(subset_indices), A.n - 1):
        carriers = hyperplanes_through_flat(A, flat)
        if len(carriers) <= len(flat):
            continue
        point = affine_intersection(A.mat[flat[0]], A.mat[flat[1]])
        if point is None:
            continue
        rounded = (round(point[0], 8), round(point[1], 8))
        if rounded not in seen:
            points.append((point, flat, carriers))
            seen.add(rounded)
    return points


def plot_constructive_state(
    A,
    subset_indices: Sequence[int],
    ax,
    title: str,
    xlim: Tuple[float, float] = (-0.5, 2.5),
    ylim: Tuple[float, float] = (-0.5, 2.5),
) -> None:
    """Plot a constructive-closure state for a rank-3 arrangement in the affine chart."""
    from matplotlib.lines import Line2D

    subset_indices = tuple(sorted(subset_indices))
    closure_indices = set(A.constructive_closure_indices(subset_indices))
    subset_set = set(subset_indices)
    added = closure_indices - subset_set

    for i, row in enumerate(A.mat.rows()):
        segment = segment_from_row(row, xlim, ylim)
        if segment is None:
            continue

        if i in subset_set:
            style = dict(color="#1f77b4", linewidth=3.0, alpha=0.95)
        elif i in added:
            style = dict(color="#ff7f0e", linewidth=3.0, alpha=0.95)
        else:
            style = dict(color="#c7c7c7", linewidth=1.5, alpha=0.9, linestyle="--")

        xs = [segment[0][0], segment[1][0]]
        ys = [segment[0][1], segment[1][1]]
        ax.plot(xs, ys, **style)

        mx = 0.5 * (xs[0] + xs[1])
        my = 0.5 * (ys[0] + ys[1])
        ax.text(mx, my, f"H{i}", fontsize=10, ha="center", va="center", backgroundcolor="white")

    for point, flat, carriers in constructive_points(A, subset_indices):
        if xlim[0] <= point[0] <= xlim[1] and ylim[0] <= point[1] <= ylim[1]:
            ax.scatter([point[0]], [point[1]], color="black", s=35, zorder=10)
            ax.annotate(
                f"flat {flat} -> {carriers}",
                point,
                xytext=(8, 8),
                textcoords="offset points",
                fontsize=9,
            )

    ax.set_xlim(*xlim)
    ax.set_ylim(*ylim)
    ax.set_aspect("equal")
    ax.grid(alpha=0.2)
    ax.set_title(title)

    legend_handles = [
        Line2D([0], [0], color="#1f77b4", lw=3, label="seed subset B"),
        Line2D([0], [0], color="#ff7f0e", lw=3, label="added by closure"),
        Line2D([0], [0], color="#c7c7c7", lw=1.5, ls="--", label="outside closure"),
        Line2D([0], [0], marker="o", color="black", lw=0, label="constructive point"),
    ]
    ax.legend(handles=legend_handles, loc="upper left", fontsize=9)
